### PR TITLE
add main_list options, to change main list

### PR DESCRIPTION
**Pull request by dyphire**

### CODE REVIEW

**Comment by Eisa01** [comment]
Nice idea! didn't think of this option.

I'll review and tesi, hopefully I didn't use display_list for some internal stuff (maybe I'm overthinking).

Though what's the difference if you change the main list instead of using a filter keybind?

**Comment by Eisa01** [comment]
Actually this gave me a nice idea of a better approach to define keybinds and list?
What do you think if I convert this option to a table that accepts two parameters, e.g.:
[ ["b", "all",], ["B", 'all'] , ["k", "keybinds"], ["K", "keybinds"] ]
This will also allow me to get rid of the specific options I am creating for each filter

**Comment by dyphire** [comment]
> Actually this gave me a nice idea of a better approach to define keybinds and filter? What do you think if I convert this option to a json table that accepts two parameters, e.g.:

It looks better

**Comment by Eisa01** [comment]
The changes mentioned have been committed.

**Pull request merged**
