### PR TITLE
fix nil values

### PR DESCRIPTION
**Pull request by dyphire**

### CODE REVIEW

**Comment by Eisa01** [comment]
Did you encounter an issue that required a check for nil within mark_chapter function?

**Comment by dyphire** [comment]
> Did you encounter an issue that required a check for nil within mark_chapter function?

When use `mark_*_as_chapter=yes` option, If the `log_file` does not exist, the script will crash due to nil values.
The pr will fix this bug.

**Review by Eisa01 — CHANGES_REQUESTED** [review]
The check needs an additional or statement for list_contents[1]:
`if not list_contents or not list_contents[1] then return end`

**Comment by dyphire** [comment]
> The check needs an additional or statement for list_contents[1]: `if not list_contents or not list_contents[1] then return end`

Done.

**Review by Eisa01 — APPROVED** [review]

**Pull request merged**
